# Google OAuth Configuration
# Replace these with your actual Google OAuth credentials

# For Local Development (http://localhost:8501)
GOOGLE_CLIENT_ID = "your_google_client_id_here"
GOOGLE_CLIENT_SECRET = "your_google_client_secret_here"
GOOGLE_REDIRECT_URI = "http://localhost:8501/"

# For Streamlit Cloud Deployment (https://your-app-name.streamlit.app)
# GOOGLE_CLIENT_ID = "your_google_client_id_here"
# GOOGLE_CLIENT_SECRET = "your_google_client_secret_here"
# GOOGLE_REDIRECT_URI = "https://your-app-name.streamlit.app/"

# Note: For local development, you need to:
# 1. Go to Google Cloud Console (https://console.cloud.google.com/)
# 2. Create a new project or select existing one
# 3. Enable Google+ API and Google OAuth2 API
# 4. Create OAuth 2.0 credentials
# 5. Add http://localhost:8501 to authorized redirect URIs
# 6. Copy the Client ID and Client Secret here 

DB_URL = "postgresql://postgres:eGJ4TFyktgYFj0SJ@db.dnydgnxcryqdruxqutnu.supabase.co:5432/postgres"