import pandas as pd
import requests
import io
from datetime import datetime, timedelta
import json

# Input CSV file generated by get_isin_codes.py (update this path if needed)
input_csv = 'smallcap_isin_codes.csv'

# Output CSV file for historical NAV data
output_csv = 'historical_nav_10_years.csv'

# Read the input CSV with ISIN codes
try:
    input_df = pd.read_csv(input_csv, sep=';', header=None, names=['MF NAME', 'ISIN CODE'])
except FileNotFoundError:
    print(f"Input file {input_csv} not found. Please run get_isin_codes.py first.")
    exit()

# Fetch the current NAVAll.txt to map ISIN to Scheme Code
url = "https://www.amfiindia.com/spages/NAVAll.txt"
response = requests.get(url)
df_navall = pd.read_csv(io.StringIO(response.text), sep=";")
df_navall_clean = df_navall.dropna(subset=['ISIN Div Payout/ ISIN Growth'])

# Calculate from_date: past 10 years
from_date = datetime.now() - timedelta(days=365*10)

# List to hold all NAV data
all_nav_data = []

# For each ISIN, get scheme code and download historical NAV
for index, row in input_df.iterrows():
    isin = row['ISIN CODE']
    mf_name = row['MF NAME']
    
    # Find scheme code for the ISIN
    mask = (df_navall_clean['ISIN Div Payout/ ISIN Growth'] == isin) | (df_navall_clean['ISIN Div Reinvestment'] == isin)
    if mask.any():
        scheme_code = str(df_navall_clean.loc[mask, 'Scheme Code'].iloc[0])
        
        try:
            # Get historical NAV using mfapi.in
            api_url = f'https://api.mfapi.in/mf/{scheme_code}'
            nav_response = requests.get(api_url)
            if nav_response.status_code == 200:
                nav_data = nav_response.json()
                if 'data' in nav_data:
                    nav_df = pd.DataFrame(nav_data['data'])
                    nav_df['Date'] = pd.to_datetime(nav_df['date'], format='%d-%m-%Y')
                    nav_df = nav_df[nav_df['Date'] >= from_date]
                    nav_df['MF NAME'] = mf_name
                    nav_df['ISIN CODE'] = isin
                    nav_df = nav_df[['Date', 'MF NAME', 'ISIN CODE', 'nav']]  # Keep relevant columns
                    all_nav_data.append(nav_df)
                else:
                    print(f"No data in response for ISIN {isin}")
            else:
                print(f"API request failed for ISIN {isin}: {nav_response.status_code}")
        except Exception as e:
            print(f"Error fetching NAV for ISIN {isin}: {e}")
    else:
        print(f"Scheme code not found for ISIN {isin}")

# Combine all NAV data
if all_nav_data:
    combined_nav_df = pd.concat(all_nav_data, ignore_index=True)
    # Sort by MF NAME, ISIN, Date
    combined_nav_df = combined_nav_df.sort_values(['MF NAME', 'ISIN CODE', 'Date'])
    combined_nav_df['Date'] = combined_nav_df['Date'].dt.strftime('%Y-%m-%d')  # Standardize date format
    combined_nav_df.to_csv(output_csv, index=False)
    print(f"Historical NAV data for the past 10 years has been written to {output_csv}")
else:
    print("No NAV data was retrieved.")